WebOA.UI/Models/UserInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebOA.UI.Models
{
    [Serializable]
    public class UserInfoViewModel
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
    }
}

WebOA.UI/Controllers/UserInfo1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebOA.Service;
using WebOA.Model;
using WebOA.Common;
using WebOA.IService;

namespace WebOA.UI.Controllers
{
    public partial class UserInfo1Controller : Controller
    {
        private UserInfoService UserInfoService = new UserInfoService();
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 获取分页数据
        /// </summary>
        /// <param name="page">PageIndex</param>
        /// <param name="rows">PageSize</param>
        /// <returns></returns>
        public ActionResult GetPageList(int page, int rows)
        {
            //接收查询数据
            int id1 = string.IsNullOrEmpty(Request["sid"]) ? 0 : int.Parse(Request["sid"]);
            string name1 = string.IsNullOrEmpty(Request["sname"]) ? "" : Request["sname"];

            //调用Service来完成查询，获取数据
            int total;
            //var result=UserInfoService.GetPageList<int>(
            //    u => (u.IsDelete == false)
            //        &&
            //        (id1==0?true:u.UserId==id1)
            //        &&
            //        (name1==""?true:u.UserName.Contains(name1)),
            //    u => u.UserId,
            //    rows, page,out total);


            WhereHelper<UserInfo> where = new WhereHelper<UserInfo>();
            where.Equal("IsDelete", false);
            if (id1 != 0)
            {
                where.Equal("UserId", id1);
            }
            if (name1 != "")
            {
                where.Contains("UserName", name1);
            }

            var result = UserInfoService.GetPageList<int>(where.GetExpression(), u => u.UserId, page, rows, out total).Select(u => new
            {
                u.UserId,
                u.UserName
            });


            return Json(new { total, rows = result }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 处理用户的添加请求
        /// </summary>
        /// <param name="userInfo">使用自动装配，完成对象的创建与初始化</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Add(UserInfo userInfo)
        {
            string result = "no";

            //完成属性值的初始化
            userInfo.IsDelete = false;
            userInfo.SubBy = 1;
            userInfo.SubTime = DateTime.Now;
            if (userInfo.Remark == null)
            {
                userInfo.Remark = "";
            }

            //对密码进行md5加密
            userInfo.UserPwd = MD5Helper.EncryptString(userInfo.UserPwd);

            //调用Service完成添加
            if (UserInfoService.Add(userInfo))
            {
                result = "ok";
            }
            return Content(result);
        }

        public ActionResult Edit(int id)
        {
            UserInfo u = UserInfoService.GetById(id);
            return View(u);//直接将对象作为View方法的参数，本质是ViewData.Model=u;
        }

        [HttpPost]
        public ActionResult Edit(UserInfo userInfo)
        {
            string result = "no";

            //装配其它值
            userInfo.SubBy = 1;
            userInfo.SubTime = DateTime.Now;
            userInfo.IsDelete = false;
            if (userInfo.Remark == null)
            {
                userInfo.Remark = "";
            }
            //判断密码是否修改
            if (userInfo.UserPwd.Trim() != "")
            {
                userInfo.UserPwd = MD5Helper.EncryptString(userInfo.UserPwd);
            }
            else
            {
                userInfo.UserPwd = Request["pwd2"];
            }

            if (UserInfoService.Edit(userInfo))
            {
                result = "ok";
            }

            return Content(result);
        }

        [HttpPost]
        public ActionResult Remove(string idList)
        {
            string result = "no";

            //将数据转换成int[]
            List<int> list = new List<int>();
            string[] ids = idList.Split(',');
            foreach (var id in ids)
            {
                list.Add(int.Parse(id));
            }

            if (UserInfoService.Remove(list.ToArray()))
            {
                result = "ok";
            }

            return Content(result);
        }
        
    }
}

WebOA.UI/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebOA.Service;
using WebOA.Model;
using WebOA.Common;
using WebOA.IService;

namespace WebOA.UI.Controllers
{
    public class UserInfoController : Controller
    {
      //  private UserInfoService userInfoService = new UserInfoService();
        public IUserInfoService  userInfoService { set; get; }
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 获取分页数据
        /// </summary>
        /// <param name="page">PageIndex</param>
        /// <param name="rows">PageSize</param>
        /// <returns></returns>
        public ActionResult GetPageList(int page, int rows)
        {
            //接收查询数据
            int id1 = string.IsNullOrEmpty(Request["sid"]) ? 0 : int.Parse(Request["sid"]);
            string name1 = string.IsNullOrEmpty(Request["sname"]) ? "" : Request["sname"];

            //调用Service来完成查询，获取数据
            int total;
            //var result=UserInfoService.GetPageList<int>(
            //    u => (u.IsDelete == false)
            //        &&
            //        (id1==0?true:u.UserId==id1)
            //        &&
            //        (name1==""?true:u.UserName.Contains(name1)),
            //    u => u.UserId,
            //    rows, page,out total);


            WhereHelper<UserInfo> where = new WhereHelper<UserInfo>();
            where.Equal("IsDelete", false);
            if (id1 != 0)
            {
                where.Equal("UserId", id1);
            }
            if (name1 != "")
            {
                where.Contains("UserName", name1);
            }

            var result = userInfoService.GetPageList<int>(where.GetExpression(), u => u.UserId, page, rows, out total).Select(u => new
            {
                u.UserId,
                u.UserName
            });


            return Json(new { total, rows = result }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 处理用户的添加请求
        /// </summary>
        /// <param name="userInfo">使用自动装配，完成对象的创建与初始化</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Add(UserInfo userInfo)
        {
            string result = "no";

            //完成属性值的初始化
            userInfo.IsDelete = false;
            userInfo.SubBy = 1;
            userInfo.SubTime = DateTime.Now;
            if (userInfo.Remark == null)
            {
                userInfo.Remark = "";
            }

            //对密码进行md5加密
            userInfo.UserPwd = MD5Helper.EncryptString(userInfo.UserPwd);

            //调用Service完成添加
            if (userInfoService.Add(userInfo))
            {
                result = "ok";
            }
            return Content(result);
        }

        public ActionResult Edit(int id)
        {
            UserInfo u = userInfoService.GetById(id);
            return View(u);//直接将对象作为View方法的参数，本质是ViewData.Model=u;
        }

        [HttpPost]
        public ActionResult Edit(UserInfo userInfo)
        {
            string result = "no";

            //装配其它值
            userInfo.SubBy = 1;
            userInfo.SubTime = DateTime.Now;
            userInfo.IsDelete = false;
            if (userInfo.Remark == null)
            {
                userInfo.Remark = "";
            }
            //判断密码是否修改
            if (userInfo.UserPwd.Trim() != "")
            {
                userInfo.UserPwd = MD5Helper.EncryptString(userInfo.UserPwd);
            }
            else
            {
                userInfo.UserPwd = Request["pwd2"];
            }

            if (userInfoService.Edit(userInfo))
            {
                result = "ok";
            }

            return Content(result);
        }

        [HttpPost]
        public ActionResult Remove(string idList)
        {
            string result = "no";

            //将数据转换成int[]
            List<int> list = new List<int>();
            string[] ids = idList.Split(',');
            foreach (var id in ids)
            {
                list.Add(int.Parse(id));
            }

            if (userInfoService.Remove(list.ToArray()))
            {
                result = "ok";
            }

            return Content(result);
        }


    }
}

WebOA.UI/Views/UserInfo/Index.cshtml
@model WebOA.Model.UserInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>用户信息表</title>
    <link href="~/Content/easyUI/icon.css" rel="stylesheet" />
    <link href="~/Content/easyUI/default/easyui.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.11.3.min.js"></script>
    <script src="~/Scripts/jquery.easyui-1.4.5.min.js"></script>
    <script src="~/Scripts/locale/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        $(function () {
            ////$('#addDiv').css("display", "none");
            //$('#addDiv').hide();
            //$('#editDiv').hide();
            //$('#setRoleDiv').hide();
            //$('#setActionDiv').hide();

            $('#btnSelect').click(function () {
                //获取查询数据
                var id1 = $('#selectId').val();
                var name1 = $('#selectName').val();
                //向服务器请求
                LoadData({
                    'sid': id1,
                    'sname': name1
                });
            });

            LoadData();
        });

        function LoadData(queryParam1) {
            $("#tt").datagrid({
                url: '@Url.Action("GetPageList")',
                title: '用户列表',
                width: 700,
                height: 400,
                fitColumns: true,
                idField: 'UserId',
                loadMsg: '正在加载用户信息...',
                pagination: true,
                singleSelect: false,
                pageSize: 10,
                pageNumber: 1,
                pageList: [10, 20, 30],
                queryParams: queryParam1,
                columns: [[
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'UserId', title: '编号', width: 80 },
                    { field: 'UserName', title: '用户名', width: 120 }
                ]],
                toolbar: [{
                    id: 'toolbarAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: AddShow
                }, {
                    id: 'toolbarEdit',
                    text: '修改',
                    iconCls: 'icon-edit',
                    handler: EditShow
                }, {
                    id: 'toolbarRemove',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: RemoveShow
                }, {
                    id: 'toolbarSetRole',
                    text: '设置角色',
                    iconCls: 'icon-cut',
                    //handler: SetRoleShow
                }, {
                    id: 'toolbarSetAction',
                    text: '设置否决',
                    iconCls: 'icon-help',
                    //handler: SetActionShow
                }]
            });
        }

        function AddShow() {
            $('#addDiv').show();

            $("#addDiv").dialog({
                title: "添加用户",
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                modal: true,

                buttons: [{
                    text: "添加",
                    iconCls: "icon-add",
                    handler: function () {
                        $("#addDiv form").submit();
                    }
                }, {
                    text: "取消",
                    iconCls: "icon-cancel",
                    handler: function () {
                        $("#addDiv").dialog("close");
                    }
                }]
            });

        }

        function AddAfter(msg) {
            if (msg == "ok") {
                $("#tt").datagrid('load');

                $('#addDiv').dialog('close');
            } else {
                alert("添加失败，请稍候重试");
            }
        }

        function EditShow() {
            //获取表格中选择的项
            var items = $('#tt').datagrid('getSelections');
            if (items.length != 1) {
                $.messager.alert('警告', "请选择一条要修改的记录");
                return;
            }
            var id = items[0]["UserId"];

            $('#editDiv').show();

            //修改src属性，指向修改页面
            $('#editDiv iframe').attr("src", '@Url.Action("Edit","UserInfo")?id=' + id);
            //以窗口的形式来显示修改页面
            $('#editDiv').dialog({
                title: "修改用户",
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                modal: true,

                buttons: [{
                    text: "修改",
                    iconCls: "icon-edit",
                    handler: function () {
                        //$('#editDiv iframe')[0].contentWindow.form.submit();
                        $('#editDiv iframe')[0].contentWindow.EditSubmit();
                    }
                }, {
                    text: "取消",
                    iconCls: "icon-cancel",
                    handler: function () {
                        $("#editDiv").dialog("close");
                    }
                }]
            });
        }

        function EditAfter(msg) {
            if (msg == "ok") {
                $('#editDiv').dialog('close');
                $('#tt').datagrid('reload');
            } else {
                $.messager.alert('提示', '修改失败，请稍候重试');
            }
        }

        function RemoveShow() {
            //获取所有选中的项
            var items = $('#tt').datagrid('getSelections');
            if (items.length <= 0) {
                $.messager.alert('警告', '请选择项之后，再进行删除操作');
                return;
            }

            //收集所有编号
            var ids = '';
            $.each(items, function (i, item) {
                ids += item['UserId'] + ',';
            });
            ids = ids.substring(0, ids.length - 1);

            //提示用户确认
            $.messager.confirm('提示', '确定要删除吗？', function (msg) {
                if (msg) {
                    //向服务器发请求
                    $.post('@Url.Action("Remove","UserInfo")', {
                        idList: ids
                    }, function (msg) {
                        if (msg == "ok") {
                            $('#tt').datagrid('reload');
                            $('#tt').datagrid('clearSelections');
                        } else {
                            $.messager.alert('提示', '删除失败，请稍候重试');
                        }
                    });
                }
            });
        }

    </script>
</head>
<body>
    <!--查询-->
    <div id="selectDiv">
        <table border="1">
            <tr>
                <td>编号：</td>
                <td><input type="text" name="selectId" id="selectId" /></td>
                <td>用户名：</td>
                <td><input type="text" name="selectName" id="selectName" /></td>
                <td><input type="button" id="btnSelect" value="查询" /></td>
            </tr>
        </table>
    </div>

    <!--用户列表-->
    <div>
        <table id="tt"></table>
    </div>

    <!--用户添加-->
    <div id="addDiv" style="display:none">
        @using (Ajax.BeginForm("Add", "UserInfo", new AjaxOptions()
            {
                OnSuccess = "AddAfter"
            }))
            {
            <table border="1">
                <tr>
                    <td>用户名：</td>
                    <td>@Html.TextBoxFor(u => u.UserName)</td>
                </tr>
                <tr>
                    <td>密码：</td>
                    <td>@Html.PasswordFor(u => u.UserPwd)</td>
                </tr>
                <tr>
                    <td>备注：</td>
                    <td>@Html.TextAreaFor(u => u.Remark)</td>
                </tr>
            </table>
        }
    </div>

    <!--用户修改-->
    <div id="editDiv"  style="display:none">
        <iframe src="/Error.html" frameborder="0" width="100%" height="100%"></iframe>
    </div>
</body>
</html>

WebOA.UI/Views/UserInfo/SetAction.cshtml
@using WebOA.Model
@model List<WebOA.Model.ActionInfo>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetAction</title>
    <script src="~/Scripts/jquery-1.11.3.min.js"></script>
    <script>
        $(function () {
            $(':radio:not(:checked)').bind('click', Click1);
        });

        function Click1() {
            //收集数据
            var uid = $('#UserId').val();
            var aid = $(this).attr('name');
            var allow = $(this).val();
                
            //发送异步请求
            $.post('@Url.Action("SetAction","UserInfo1")', {
                    uid: uid,
                    aid: aid,
                    allow: allow
                }, function(msg) {
                    if (msg != "ok") {
                        alert('分配否决失败，请稍候重试');
                    }
                });
                
            //处理绑定事件，防止用户多次点击已选中的单选按钮
            $(this).unbind('click').siblings().unbind('click').bind('click', Click1);
        }
    </script>
</head>
<body>
    <div>
        @{
            UserInfo userInfo = ViewBag.UserInfo as UserInfo;
            List<UserAction> list = ViewBag.UserAction as List<UserAction>;
        }
        <input type="hidden" id="UserId" value="@userInfo.UserId"/>
        <table border="1">
            <thead>
                <th>权限名称</th>
                <th>设置</th>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ActionTitle</td>
                        <td>
                            <input type="radio" name="@item.ActionId"
                                @if (list.Where(ua=>(ua.ActionId==item.ActionId)&&(ua.IsAllow==true)).Count()>0)
                                    {
                                        @(" checked='checked'");
                                    }
                                   value="1"/>允许&nbsp;&nbsp;
                            

                            <input type="radio" name="@item.ActionId" 
                                @if (list.Where(ua=>(ua.ActionId==item.ActionId)&&(ua.IsAllow==false)).Count()>0)
                                    {
                                        @(" checked='checked'");
                                    }
                                   value="-1"/>拒绝&nbsp;&nbsp;
                            

                            <input type="radio" name="@item.ActionId"
                                @if (list.Where(ua=>(ua.ActionId==item.ActionId)).Count()==0)
                                    {
                                        @(" checked='checked'");
                                    }
                                   value="0"/>取消
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

WebOA.UI/Views/UserInfo/SetRole.cshtml
@using WebOA.Model
@model List<WebOA.Model.RoleInfo>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetRole</title>
    <script src="~/Scripts/jquery-1.11.3.min.js"></script>
    <script>
        function SetRoleDeal() {
            //获取所有选中的项
            var ids = '';
            $(':checked').each(function() {
                ids += $(this).val() + ',';
            });
            if (ids == '') {
                alert('请选择角色后再设置');
                return;
            }
            ids = ids.substring(0, ids.length - 1);

            var uid1 = $('#UserId').val();
            
            //向服务器端发请求
            $.post('@Url.Action("SetRole","UserInfo1")', {
                    uid: uid1,
                    rids: ids
                }, function(msg) {
                    window.parent.SetRoleAfter(msg);
                });
        }
    </script>

</head>
<body style="padding: 0px; margin: 0px;">
    <div>
        
        @{
            var userInfo = ViewBag.UserInfo as UserInfo;
           <input  type="hidden" name="UserId" id="UserId" value="@userInfo.UserId"/><br/>
            int counter = Model.Count;
            for (int i = 0; i < counter; i++)
            {
                <input type="checkbox" value="@Model[i].RoleId"
                    
                    @if (userInfo.RoleInfo.Contains(Model[i]))
                    {
                        @Html.Raw("checked='checked'")
                    }
                    
                    />@Model[i].RoleName
                if ((i+1)%4 == 0)
                {
                    <br/>
                }
            }
        }
    </div>
</body>
</html>